export { default as Main } from "./Main";
export { default as Login } from "./Login";
export { default as LogOut } from "./LogOut";
export { default as NavBar } from "./NavBar";
export { default as Posts } from "./Posts";
export { default as SinglePost } from "./SinglePost";
export { default as Search } from "./Search";
export { default as EditPostCard } from "./EditPostCard";
export { default as NewPost } from "./NewPosts";
export { default as SignUp } from "./SignUp";
// export { default as Profile } from "./Profile";
// export { default as Register } from "./Register";
